#!/bin/bash
pwd | grep -q "node_modules"
if [ -z $(pwd | grep -q 'node_modules') ]; then
	if [ package.json -nt .git/.npm_installed ]; then
		npm install
		if [ -d node_modules ]; then
			touch .git/.npm_installed
		fi
	fi
fi

# emit a notification and in the future, perhaps do a lot lot more
if [ $(which growlnotify) ]; then

print_js=$(cat <<END_NODE
require('shelljs/global');
var Growl = require('growl');
var res = exec("repo info .");
var i, nl, out = res.output;
if(!res.code && typeof out === 'string' && ~(i = out.indexOf("Project: ")) && ~(nl = out.indexOf('\n', i))) {
	project = out.substring(i + "Project:".length, nl ).trim();
}
Growl("updated "+project, {title: "Blueshift", image: './icons/success.png'});
END_NODE)
node -e "$print_js" 2> /dev/null

fi
